# ip package

name: ip
parent: default

matches:
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo -n $(curl ifconfig.me)"
